"""The worked example, run for real.

Hindsight's own scenarios are generated by code that lives in this repository, so
they cannot answer "does this work on data you did not create?". This example is
committed CSV in a different domain, with different column names and a different
leak mechanism, and this test runs the real audit against it.

If this test fails, the claim that the adapter reads external data is no longer
true, whatever the documentation says.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from hindsight.validation.point_in_time import run_credit_validation

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCENARIO = PROJECT_ROOT / "examples" / "adapter" / "scenario.json"


@pytest.fixture(scope="module")
def report() -> dict:
    return run_credit_validation(SCENARIO)


def test_the_example_data_is_committed() -> None:
    """A judge should not have to generate anything to check this."""
    for name in ("retention_decisions.csv", "plan_change_history.csv", "scenario.json"):
        assert (SCENARIO.parent / name).is_file(), name


def test_the_audit_passes_every_check_on_external_data(report: dict) -> None:
    assert report["status"] == "passed", report["checks"]
    for name, passed in report["checks"].items():
        assert passed, name


def test_the_leak_is_found_and_collapses(report: dict) -> None:
    case = report["leakage_case"]
    # Nearly all of the apparent skill came from records that did not exist yet.
    assert case["observed_auc"] > 0.95
    assert case["advantage_retained"] < 0.10
    assert case["collapsed"] is True
    assert report["reconstruction"]["excluded_post_cutoff_records"] > 0


def test_the_honest_rebuild_lands_back_near_baseline(report: dict) -> None:
    """The point of the example: the leaky feature was worth almost nothing."""
    case = report["leakage_case"]
    assert abs(case["point_in_time_auc"] - case["baseline_auc"]) < 0.02


def test_the_safe_control_still_clears_on_external_data(report: dict) -> None:
    """A detector that flags whatever is predictive would fail here."""
    control = report["safe_control"]
    assert control["collapsed"] is False
    assert control["advantage_retained"] > 0.5


def test_it_reads_the_scenario_s_own_identities_not_the_credit_defaults() -> None:
    """A churn audit must not emit credit-risk case ids or lineage."""
    context = run_credit_validation(SCENARIO)["evidence_context"]
    assert context["leakage_case_id"] == "churn-post-decision-plan-change"
    assert "credit" not in json.dumps(context).lower()
    assert context["leakage_lineage_path"][0].startswith("plan_change_history.")


def test_an_adapter_scenario_without_identities_is_refused(tmp_path: Path) -> None:
    """Silently borrowing another domain's identities is the worse failure.

    Before this guard, a scenario that pointed at its own data but forgot
    audit_evidence produced a report claiming credit-default case ids and
    prior_delinquencies lineage over someone else's dataset.
    """
    config = json.loads(SCENARIO.read_text(encoding="utf-8"))
    del config["audit_evidence"]

    # Keep the data paths resolvable from the temporary scenario file.
    adapter = config["point_in_time_adapter"]
    for key in ("applications", "feature_records"):
        adapter[key]["path"] = str(SCENARIO.parent / adapter[key]["path"])

    path = tmp_path / "no_identities.json"
    path.write_text(json.dumps(config), encoding="utf-8")

    with pytest.raises(ValueError, match="must declare audit_evidence"):
        run_credit_validation(path)


def test_the_committed_data_is_reproducible_from_the_generator() -> None:
    """The generator is the record of how the example was made."""
    script = PROJECT_ROOT / "scripts" / "make_adapter_example.py"
    assert script.is_file()
    body = script.read_text(encoding="utf-8")
    assert "SEED = " in body, "the example must be deterministic"


# --- Wide snapshot tables ---------------------------------------------------
#
# Long-form event histories are the convenient shape. Most warehouses keep
# features wide instead: one row per entity per as-of date, a column per feature.
# The same leak has to be findable there, or the adapter only serves teams who
# already store data the way this tool prefers.


def _wide_snapshots_from_the_example(tmp_path: Path) -> Path:
    """Rewrite the committed long-form history as a wide snapshot table."""
    import csv

    rows: dict[tuple[str, str], dict[str, str]] = {}
    history = SCENARIO.parent / "plan_change_history.csv"
    with history.open(encoding="utf-8") as handle:
        for record in csv.DictReader(handle):
            key = (record["subscriber"], record["recorded_at"])
            rows[key] = {
                "cust": record["subscriber"],
                "as_of": record["recorded_at"],
                # A second, unrelated column, so the file is genuinely wide and
                # the adapter has to pick the right one.
                "logins_30d": "7",
                "plan_changes_to_date": record["plan_changes_to_date"],
            }

    wide = tmp_path / "feature_snapshots.csv"
    with wide.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=["cust", "as_of", "logins_30d", "plan_changes_to_date"]
        )
        writer.writeheader()
        for record in rows.values():
            writer.writerow(record)

    config = json.loads(SCENARIO.read_text(encoding="utf-8"))
    adapter = config["point_in_time_adapter"]
    adapter["kind"] = "wide_snapshots"
    adapter["applications"]["path"] = str(SCENARIO.parent / adapter["applications"]["path"])
    del adapter["feature_records"]
    adapter["feature_snapshots"] = {"path": str(wide), "format": "csv"}

    columns = adapter["columns"]
    for gone in ("record_entity_id", "available_time", "feature_value"):
        del columns[gone]
    columns["snapshot_entity_id"] = "cust"
    columns["snapshot_time"] = "as_of"
    columns["feature"] = "plan_changes_to_date"

    path = tmp_path / "wide_scenario.json"
    path.write_text(json.dumps(config), encoding="utf-8")
    return path


def test_the_same_leak_is_found_in_a_wide_snapshot_table(tmp_path: Path) -> None:
    wide = run_credit_validation(_wide_snapshots_from_the_example(tmp_path))
    assert wide["status"] == "passed", wide["checks"]
    assert wide["leakage_case"]["collapsed"] is True
    assert wide["reconstruction"]["excluded_post_cutoff_records"] > 0


def test_wide_and_long_form_agree_on_the_verdict(tmp_path: Path) -> None:
    """Two shapes of the same facts must not produce two different answers."""
    long_form = run_credit_validation(SCENARIO)
    wide = run_credit_validation(_wide_snapshots_from_the_example(tmp_path))

    assert wide["status"] == long_form["status"]
    assert wide["leakage_case"]["collapsed"] == long_form["leakage_case"]["collapsed"]
    assert wide["leakage_case"]["observed_auc"] == pytest.approx(
        long_form["leakage_case"]["observed_auc"], abs=1e-9
    )
    assert wide["leakage_case"]["point_in_time_auc"] == pytest.approx(
        long_form["leakage_case"]["point_in_time_auc"], abs=1e-9
    )


def test_the_report_records_which_shape_it_read(tmp_path: Path) -> None:
    wide = run_credit_validation(_wide_snapshots_from_the_example(tmp_path))
    assert wide["reconstruction"]["input"]["adapter"] == "wide_snapshots"
    assert "feature_snapshots" in wide["reconstruction"]["input"]
