"""Record the external-data audit and sweep, for the evidence page to display.

The console must not run these on request: a public demo that retrains a model
when a stranger loads a page is a CPU tarpit. So the numbers are produced here,
committed, and rendered as a record.

Recording numbers creates a way for a page to drift from the truth, so
`tests/test_external_proof.py` re-runs both and asserts the committed values
still match. If the behaviour changes, that test fails rather than the website
quietly showing last week's result.

    uv run python scripts/record_external_proof.py
"""

from __future__ import annotations

import json
from pathlib import Path

from hindsight.sweep import sweep
from hindsight.validation.point_in_time import run_credit_validation

ROOT = Path(__file__).resolve().parents[1]
EXAMPLE = ROOT / "examples" / "adapter"
OUT = ROOT / "evidence" / "adapter" / "external-data-proof.json"


def main() -> int:
    long_form = run_credit_validation(EXAMPLE / "scenario.json")
    wide = run_credit_validation(EXAMPLE / "scenario_wide.json")
    swept = sweep(EXAMPLE / "scenario_wide.json")

    case = long_form["leakage_case"]
    control = long_form["safe_control"]

    payload = {
        "schema_version": 1,
        "what_this_is": (
            "Hindsight's own scenarios are generated by code in this repository, so they "
            "cannot show whether it works on data it did not create. This is a committed "
            "dataset in a different domain, with different column names and a different "
            "leak mechanism, audited by the same deterministic routes."
        ),
        "dataset": {
            "domain": "Subscription churn",
            "decision": "Should the retention team intervene before this subscriber churns?",
            "rows": long_form["rows"],
            "leak": (
                "plan_changes_to_date is a running counter, and the training table joined in "
                "every change ever recorded - including the downgrade a customer makes while "
                "cancelling. Before the decision it is close to noise; after it, nearly the label."
            ),
            "files": [
                {
                    "name": name,
                    "what": what,
                    "bytes": (EXAMPLE / name).stat().st_size,
                    "lines": len((EXAMPLE / name).read_text(encoding="utf-8").splitlines()),
                }
                for name, what in (
                    (
                        "retention_decisions.csv",
                        "One row per subscriber: the decision, the "
                        "outcome, and what was knowable at the time",
                    ),
                    (
                        "plan_change_history.csv",
                        "A running count of plan changes, each row "
                        "stamped with when it was recorded",
                    ),
                    (
                        "feature_snapshots.csv",
                        "The same facts as a wide feature table, one row "
                        "per subscriber per as-of date",
                    ),
                    ("scenario.json", "Maps those column names onto the audit contract"),
                    ("scenario_wide.json", "The wide-table variant, with the sweep candidates"),
                )
            ],
        },
        "result": {
            "status": long_form["status"],
            "baseline_auc": round(case["baseline_auc"], 4),
            "observed_auc": round(case["observed_auc"], 4),
            "point_in_time_auc": round(case["point_in_time_auc"], 4),
            "observed_advantage": round(case["observed_advantage"], 4),
            "advantage_retained_pct": round(case["advantage_retained"] * 100, 2),
            "collapsed": case["collapsed"],
            "excluded_post_cutoff_records": long_form["reconstruction"][
                "excluded_post_cutoff_records"
            ],
            "safe_control_collapsed": control["collapsed"],
        },
        "wide_table_agrees": {
            "status": wide["status"],
            "observed_auc_matches": abs(wide["leakage_case"]["observed_auc"] - case["observed_auc"])
            < 1e-9,
            "point_in_time_auc_matches": abs(
                wide["leakage_case"]["point_in_time_auc"] - case["point_in_time_auc"]
            )
            < 1e-9,
            "why_it_matters": (
                "Most feature stores are wide - one row per entity per as-of date - rather "
                "than an event log. Two shapes of the same facts must not produce two answers."
            ),
        },
        "sweep": {
            "ranked_by": swept["ranked_by"],
            "flagged": swept["flagged"],
            "how_to_read_this": swept["how_to_read_this"],
            "findings": [
                {
                    "feature": item["feature"],
                    "observed_auc": item["observed_auc"],
                    "point_in_time_auc": item["point_in_time_auc"],
                    "advantage_lost": item["advantage_lost"],
                    "collapsed": item["collapsed"],
                }
                for item in swept["findings"]
                if item["status"] == "evaluated"
            ],
            "the_trap": (
                "support_tickets_snapshot scores far above the baseline and loses nothing to "
                "the cutoff. Ranked by importance it would sit near the top; ranked by "
                "advantage lost it is correctly at zero."
            ),
        },
        "commands": [
            "uv run hindsight validate-point-in-time --scenario examples/adapter/scenario.json",
            "uv run hindsight validate-point-in-time"
            " --scenario examples/adapter/scenario_wide.json",
            "uv run hindsight sweep-features --scenario examples/adapter/scenario_wide.json",
        ],
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(
        f"  observed {payload['result']['observed_auc']}"
        f" -> point-in-time {payload['result']['point_in_time_auc']}"
    )
    print(
        f"  retained {payload['result']['advantage_retained_pct']}%"
        f"  flagged {payload['sweep']['flagged']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
